site_url: https://mrtnvh.com
backend:
  name: git-gateway
  accept_roles:
    - Admin
media_folder: "static/media"
public_folder: "media"
collections:
  - name: "project"
    label: "Projects"
    folder: "content/project"
    create: true
    slug: "{{slug}}"
    identifier_field: "title"
    fields:
      - label: "Title"
        name: "title"
        widget: "string"
      - label: "Subtitle"
        name: "subtitle"
        widget: "string"
      - label: "Color"
        name: "color"
        widget: "color"
      - label: "Featured Image"
        name: "thumbnail"
        widget: "image"
        media_library:
          config:
            multiple: false
      - label: "Body"
        name: "body"
        widget: "markdown"
