name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: 12.x

      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      - name: Run build
        run: 'npm run generate'
        env:
          CI: true
