name: Build, test & deploy

on:
  push:
    branches:
      - main
      - develop
  pull_request:

env:
  CI: true

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        uses: bahmutov/npm-install@v1
        with:
          install-command: npm ci

      - name: Run build
        run: 'npm run build'
        env:
          CI: true

      - name: Archive build output
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: dist
          retention-days: 1

  test:
    runs-on: macos-12

    needs: build

    strategy:
      matrix:
        node-version: [16.x]
        test-type: ['lint', 'style', 'e2e']

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        uses: bahmutov/npm-install@v1
        with:
          install-command: npm ci --legacy-peer-deps

      - name: Install Playwright deps
        run: npx playwright install-deps chromium

      - name: Download build artifact
        uses: actions/download-artifact@v3
        with:
          name: build
          path: dist

      - name: Run ${{ matrix.test-type }}
        run: 'npm run test:${{ matrix.test-type }}'

      - name: Archive snapshot artifacts
        uses: actions/upload-artifact@v3
        continue-on-error: true
        if: ${{ success() || failure() }}
        with:
          name: playwright-results
          path: test-results
          retention-days: 5

  deploy-preview:
    runs-on: ubuntu-latest

    needs: build

    outputs:
      deployment: ${{ steps.deployment-preview.outputs.preview-url || steps.deployment-staging.outputs.preview-url || steps.deployment-prod.outputs.preview-url }}

    steps:
      - uses: actions/checkout@v3

      - name: Download build artifact
        uses: actions/download-artifact@v3
        with:
          name: build
          path: dist

      - name: Upload to Vercel (Preview)
        id: deployment-preview
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID}}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID}}

  lighthouse:
    runs-on: ubuntu-latest

    needs: deploy-preview

    env:
      CI_BASEURL: ${{needs.deploy-preview.outputs.deployment}}

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Get URLS from sitemap
        id: urls
        uses: actions/github-script@v6
        with:
          script: |
            const { XMLParser } = require("fast-xml-parser");
            const fs = require("fs");

            function getPages() {
              const sitemapFileName = fs
                .readdirSync(`dist`)
                .reduce((acc, fileName) => (fileName.includes("sitemap-0") ? fileName : acc), "");
              const sitemap = fs.readFileSync('${{ github.workspace }}/dist/${sitemapFileName}', "utf-8");
              const parser = new XMLParser();
              const sitemapJson = parser.parse(sitemap);
              const pages = sitemapJson.urlset.url
                .map(({ loc }) => {
                  const url = new URL(loc);
                  return `${process.env.CI_BASEURL}${url.pathname}`;
                })
                .filter((pathname: string) => !pathname.includes("kitchensink"));
              return pages;
            }
            core.setOutput('urls', getPages().join('\n'));

      - name: Audit URLs using Lighthouse
        uses: treosh/lighthouse-ci-action@v10
        with:
          urls: |
            ${{ steps.urls.outputs.urls }}
          # budgetPath: ./budget.json
          uploadArtifacts: true

  deploy:
    runs-on: ubuntu-latest

    needs: [build, test, lighthouse]

    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop'

    steps:
      - uses: actions/checkout@v3

      - name: Download build artifact
        uses: actions/download-artifact@v3
        with:
          name: build
          path: dist

      - name: Upload to Vercel (Staging)
        id: deployment-staging
        uses: amondnet/vercel-action@v25
        if: github.ref == 'refs/heads/develop'
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID}}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID}}
          alias-domains: |
            staging.mrtnvh.com

      - name: Upload to Vercel (Production)
        id: deployment-prod
        uses: amondnet/vercel-action@v25
        if: github.ref == 'refs/heads/main'
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID}}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID}}
          vercel-args: '--prod'
