name: Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 12.x
        uses: actions/setup-node@v2
        with:
          node-version: 12.x

      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      - name: Run build
        run: "npm run build"
        env:
          CI: true

  test:
    runs-on: macos-10.15

    needs: build

    strategy:
      matrix:
        node-version: [12.x]
        test-type: [test, lint, stylelint]

    steps:
      - name: Run ${{ matrix.test-type }}
        run: "npm run ${{ matrix.test-type }}"
        env:
          CI: true

      - name: Archive snapshot artifacts
        uses: actions/upload-artifact@v2
        if: ${{ matrix.test-type }} == test
        with:
          name: snapshots
          path: tests/__image_snapshots__
          retention-days: 5
