name: Tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: 12.x

      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      - name: Run build
        run: 'npm run generate'
        env:
          CI: true

      - name: Upload build result
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist

  test:
    runs-on: macos-10.15

    strategy:
      matrix:
        node-version: [12.x]
        test-type: [lint, style, e2e, visual, performance]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      - name: Upload build result
        uses: actions/upload-artifact@v2
        with:
          name: dist

      - name: Run ${{ matrix.test-type }}
        run: 'npm run test:${{ matrix.test-type }}'
        env:
          CI: true

      - name: Archive snapshot artifacts
        uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
          name: snapshots
          path: tests/visual/__image_snapshots__
          retention-days: 5
